services:
  db:
    image: postgres:16-alpine
    container_name: currencytracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 26eses26
      POSTGRES_DB: CurrencyTrackerDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: